name: open_meteo_api
description: Open-Meteo API Client
version: 0.0.1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  http: ^0.13.0
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  very_good_analysis: ^4.0.0
  mocktail: ^0.3.0
  test: ^1.24.1