name: bloc_weather
description: Bloc Weather :)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  google_fonts: ^3.0.1
  hydrated_bloc: ^9.1.0
  json_annotation: ^4.8.0
  path_provider: ^2.0.14
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.0
  mocktail: ^0.3.0
  test: ^1.0.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true