name: weather_repository
description: Weather Repository
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  open_meteo_api:
    path: ../open_meteo_api

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  mocktail: ^0.3.0
  test: ^1.24.1
  very_good_analysis: ^4.0.0